CREATE SCHEMA skostr;
USE skostr;

CREATE TABLE user (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
age INT NOT NULL,
mail VARCHAR(100) NOT NULL,
shoe_size FLOAT NOT NULL,
date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);